import os
import time
import subprocess
import requests
from dotenv import load_dotenv

# Load API keys
load_dotenv()

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
REPO_OWNER = "kuru2388"
REPO_NAME = "-auto-fixer_test_app" 

def run_command(command):
    """Runs a terminal command behind the scenes"""
    try:
        result = subprocess.run(command, shell=True, capture_output=True, text=True, check=True)
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"Command failed: {e.stderr}")
        return None

def push_and_create_pr(ticket_id, diagnosis_text):
    """Automates the git workflow safely and opens a PR"""
    # 🟢 FIX: Adding a timestamp so the branch name is ALWAYS unique!
    branch_name = f"fix/{ticket_id.lower()}-{int(time.time())}"
    
    print(f"🌿 1. Preparing branch: {branch_name}")
    # Switch to main and clean up any old local version of this branch safely
    run_command("git checkout main")
    # We can ignore the delete command failing if the branch doesn't exist yet
    run_command(f"git branch -D {branch_name}") 
    run_command(f"git checkout -b {branch_name}")
    
    print("💾 2. Staging specific code files...")
    run_command("git add main.py vision.py ai.py github_agent.py .gitignore")
    run_command(f'git commit -m "Auto-fix applied for {ticket_id}"')
    
    print("🚀 3. Pushing branch to GitHub...")
    push_result = run_command(f"git push -u origin {branch_name} --force")
    if push_result is None:
        print("❌ Push failed. Check your GitHub token permissions.")
        return None
    
    print("📥 4. Opening Pull Request...")
    url = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/pulls"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    
    data = {
        "title": f"Auto-Fix: {ticket_id}",
        "body": f"Automated fix generated by AI Agent.\n\n**Diagnosis:**\n{diagnosis_text}",
        "head": branch_name,
        "base": "main"
    }
    
    response = requests.post(url, headers=headers, json=data)
    if response.status_code == 201:
        pr_url = response.json().get("html_url")
        print(f"✅ Pull Request created successfully: {pr_url}")
        return pr_url
    else:
        print(f"❌ PR failed. GitHub says: {response.json()}")
        return None

# Quick test block to run this file on its own
if __name__ == "__main__":
    print("Testing github_agent.py directly...")
    pr = push_and_create_pr("AUT-5", "Dummy diagnosis fix")
    print(f"PR Link: {pr}")